config/routes.rb
Rails.application.routes.draw do
  
  resources :comments
  root "pages#home"
  get "about", to: "pages#about"
  resources :articles
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  post 'users', to: 'users#create'

end

app/models/article.rb
class Article < ActiveRecord::Base
	belongs_to :user
	validates :title, presence: true, length: {minimum: 3, maximum: 50}
	validates :description, presence: true, length: {minimum: 3, maximum: 50}
	validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :articles
	before_save {self.email = email.downcase}
	validates :username, presence: true,uniqueness:{case_sensitive: false}, length: {minimum: 3, maximum: 25}
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence:true, length: {maximum: 105},
				uniqueness: {case_sensitive: false},
				format: {with: VALID_EMAIL_REGEX}
	has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	before_action :set_article, only: [:edit, :update, :show, :destroy]
	def index
		@articles = Article.all
	end

	def new
		@article = Article.new
	end
	def create
		@article = Article.new(article_params)
		@article.user= User.first
		if @article.save
			flash[:notice] = "Article was successfully created"
			redirect_to article_path(@article)
		else
			render 'new'
		end
	end

	def edit
		set_article
	end

	def update
		
		if @article.update(article_params)
			flash[:notice] = "Article was successfully updated"
			redirect_to article_path(@article)
		else
			render 'edit'
		end
	end

	def show
		
	end

	def destroy
		
		@article.destroy
		flash[:notice] = "deleted"
		redirect_to articles_path
	end
	
	private

		def set_article
			@article = Article.find(params[:id])
			
		end
		def article_params
			params.require(:article).permit(:title, :description)
		end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def home
	end
	def about
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		@users = User.all
	end
	
	def new
		@user=User.new
	end
	def create
		@user = User.new(user_params)
		if @user.save
			flash[:success]="welcome #{@user.username}"
			redirect_to articles_path
		else
			render 'new'
		end
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		if @user.update(user_params)
			flash[:success]= "updated"
			redirect_to articles_path
		else
			render 'edit'
		end
	end

	def show
		@user = User.find(params[:id])
	end


	private
	def user_params
		params.require(:user).permit(:username,:email,:password)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_article.html.erb
<%= link_to "create new article", new_article_path %>
<table>
	<tr>
		<th>Title</th>
		<th>Description</th>
	</tr>
	<% obj.each do |article| %>
	<tr>
		<td><%= article.title %> </td>
		<td><%= article.description %> </td>
		<td><%= link_to 'Edit', edit_article_path(article) %></td>
		<td><%= link_to 'show', article_path(article)%></td>
		<td><%= link_to 'Delete', article_path(article), method: :delete, data: {confirm: "Are u sure"} %></td>
		<td> Created by: <%= article.user.username %>
			<%= time_ago_in_words(article.created_at)%> ago,
			last updated: <%= time_ago_in_words(article.updated_at)%>ago</td>
	</tr>
	<%end%>
</table>

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
<h2>following fucked up <h2>
<ul>
<% @article.errors.full_messages.each do |msg|%>
<li><%= msg %></li>
<%end%>
<%end%>

<%= form_for @article do |f| %>
<p>
	<%= f.label :title %> 
	<%= f.text_field :title %>
</p>
<p>
	<%= f.label :description %>
	<%= f.text_area :description %>
</p>
<p>
	<%= f.submit %>
</p>
<% end %>

<%= link_to "back to listing", articles_path %>

app/views/articles/edit.html.erb
<h1>edit</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1> List </h1>
<%= render 'article', obj: @articles%>

app/views/articles/new.html.erb
<h1>Create an art<h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h1>Showing selected article</h1>
<p>Title: <%= @article.title %>
</p>

<p>
Description: <%= @article.description %>
	<ul class="listing">
		<div class="row">
				<li><%= user_path(@article.user) %> </li>
				<li class="article-title">
					<%= link_to @article.user.username, user_path(@article.user) %>
				</li>
				<li>
					<small>
						<%= pluralize(@article.user.articles.count, "article") if @article.user.articles %>
				</small>
				</li>
				</div>
</p>
<%= link_to "edit this article", edit_article_path(@article)%> |
<%= link_to "back to listing", articles_path %>

app/views/layouts/_messages.html.erb
	<% flash.each do |name,msg| %>
	<ul>
		<li> <%= msg %>
	</ul>
	<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TestAp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/messages'%>
<%= yield %>

</body>
</html>

app/views/pages/about.html.erb
<%= link_to 'home', root_path %>

app/views/pages/home.html.erb
<%= link_to "alpha blog",articles_path %> | <%= link_to 'About', about_path %>

app/views/users/_form.html.erb
<% if @user.errors.any? %>
<h2>following fucked up <h2>
<ul>
<% @user.errors.full_messages.each do |msg|%>
<li><%= msg %></li>
<%end%>
<%end%>

<%= form_for @user do |f| %>
<p>
	<%= f.label :username %> 
	<%= f.text_field :username %>
</p>
<p>
	<%= f.label :email %>
	<%= f.email_field :email %>
</p>
<p>
	<%= f.label :password %>
	<%= f.password_field :password %>
</p>
<p>
	<%= f.submit %>
</p>
<% end %>

<%= link_to "back to listing", articles_path %>

app/views/users/edit.html.erb
<h1>edit<h1>
<%= render 'form' %> 

app/views/users/index.html.erb
<h1 align="center">Bloggers</h1>
<% @users.each do |user| %>
	<ul class="listing">
		<div class="row">
			<div class="well">
				<li><%= user_path(user) %> </li>
				<li class="article-title">
					<%= link_to user.username, user_path(user) %>
				</li>
				<li>
					<small>
						<%= pluralize(user.articles.count, "article") if user.articles %>
				</small>
				</li>
				</div>
				</div>
<%end%>

app/views/users/new.html.erb
<h1 align="center"> Signup <h1>
<%= render 'form' %>

app/views/users/show.html.erb
<h1 align="center">Welcome <%= @user.username %>'s page </h1>
<%= render 'articles/article', obj:@user.articles%>